version: '3.9'

services:
  db:
    build: ./db
    container_name: postgres_db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DATABASE=postgresql
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./db/db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: nestjs_api
    entrypoint: ./entrypoint.sh
    ports:
      - '3000:3000'  # porta da API
      - '5555:5555'  # porta do Prisma Studio (opcional)
    volumes:
      - .:/home/node/api  # sincroniza os arquivos locais com o container
    depends_on:
      - db  # garante que o banco rode antes da API

volumes:
  postgres_data:
